version: '3'

services:
 unbound:
  image: mvance/unbound-rpi:latest
  container_name: unbound-n
  restart: always
  ports:
   - 53:53/tcp
   - 53:53/udp
  networks:
      macvlan0:
        ipv4_address: 192.168.2.229
  volumes:
   - ./data:/opt/unbound/etc/unbound
networks:
  macvlan0:
    external: true
